version: '3'

services:
  database:
    image: 'postgres:latest'

    ports:
      - "${DB_PORT}:${DB_PORT}"

    restart: always

    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080